config/routes.rb
Rails.application.routes.draw do
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :cards
      resources :users
      resources :sessions
    end
  end 

  root "cards#index"
  
  resources :users
  resources :sessions
  resources :cards

  scope '/registration' do
    get "logout" => "sessions#destroy", :as => "logout"
    get "login" => "sessions#new", :as => "login"
    get "signup" => "users#new", :as => "signup"

    post "oauth/callback" => "oauths#callback"
    get "oauth/callback" => "oauths#callback" # for use with Github
    get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider
    delete "oauth/:provider" => "oauths#destroy", :as => :delete_oauth
  end
end

app/views/shared/_alert_notice.html.erb
<% if flash[:alert] || flash[:notice]%>
  <div class="col-sm-12">
    <% if flash[:notice]%>
      <div class="alert alert-info alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span></button>
        <p id="alert"><%= flash[:notice] %></p>
      </div>
    <% end %>
    <% if flash[:alert]%>
      <div class="alert alert-warning alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span></button>
        <p id="alert"><%= flash[:alert] %></p>
      </div>
    <% end %>
  </div>
<% end %>

app/views/shared/_header.html.erb
<div class="row" id="header">
  <div class="col-sm-12">
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="collapse navbar-collapse navbar-right">
          <%= link_to "New card", new_card_path %>
          <% if logged_in? %>
            Currently logged in as: <%= current_user.email %>
            <%= link_to "Log out", logout_path %>
          <% else %>
            <%= link_to "Sign up", signup_path %> | 
            <%= link_to "Sign in", login_path %> | 
            <%= link_to 'Login using Github', auth_at_provider_path(provider: :github) %> | 
            <%= link_to 'Login using Google', auth_at_provider_path(provider: :google) %>
          <% end %>
        </div>
      </div>
    </nav>
  </div>
</div>