config/routes.rb
Rails.application.routes.draw do
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :cards
      resources :users
      resources :sessions
    end
  end 

  root "cards#index"
  
  resources :users
  resources :sessions
  resources :cards

  scope '/registration' do
    get "logout" => "sessions#destroy", :as => "logout"
    get "login" => "sessions#new", :as => "login"
    get "signup" => "users#new", :as => "signup"

    post "oauth/callback" => "oauths#callback"
    get "oauth/callback" => "oauths#callback" # for use with Github
    get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider
    delete "oauth/:provider" => "oauths#destroy", :as => :delete_oauth
  end
end

app/models/card.rb
class Card < ApplicationRecord
  default_scope { where(public_status: false) }
  belongs_to :user 

end

app/controllers/api/v1/cards_controller.rb
module Api
  module V1
    class CardsController < ApplicationController
      respond_to :json

      def index
        respond_with Card.all.order('created_at DESC')
      end

      def show
        respond_with Card.find(params[:id])
      end
    end
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  # before_action :require_login, :only => :new
  before_action :authenticate, :only => :new
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  def index
    @cards = Card.all.order('created_at DESC')
  end

  def new
    @card = current_user.cards.new
  end

  def create
    @card = current_user.cards.build(card_params)
    if @card.save
      redirect_to cards_path
    else
      redirect_to @card 
    end
  end

  def show
  end

  def edit
  end

  def update
    if @card.update(card_params)
      redirect_to @card
    else
      render 'new'
    end
  end

  def destroy
    @card.destroy

    redirect_to root_path
  end

  private
    def set_card
      @card = Card.find(params[:id])
    end

    def card_params
      params.require(:card).permit(:title, :body, :status)
    end
end

app/views/cards/_form.html.erb
<%= simple_form_for @card do |f| %>
  <div class="form-group">
    <%= f.input :title, label: "Title:", 
                input_html: { class: 'form-control', required: true, autofocus: true } %>
  </div>
  <div class="form-group">
    <%= f.input :body, label: "Decision:", 
                input_html: { class: 'form-control', required: true, autofocus: true } %>
  </div>
  <div class="form-group">
    <%= f.input :public_status, as: :boolean, boolean_style: :inline %>
  </div>
  <%= f.button :submit, "Create card", class: 'btn btn-default' %>
<% end%>

app/views/cards/edit.html.erb
<h1>Edit Card</h1>

<%= render 'form' %>

app/views/cards/index.html.erb
<% @cards.each do |card| %>
  <div class="card_wrapper">
    <h2 class="title"><%= link_to card.title, card %></h2>
    <p class="date"><%= card.created_at.strftime("%B, %d, %Y") %></p>
  </div>
<% end %>

app/views/cards/new.html.erb
<h1>New Card</h1>

<%= simple_form_for @card do |f| %>
  <div class="form-group">
    <%= f.input :title, label: "Title:", 
                input_html: { class: 'form-control', required: true, autofocus: true } %>
  </div>
  <div class="form-group">
    <%= f.input :body, label: "Decision:", 
                input_html: { class: 'form-control', required: true, autofocus: true } %>
  </div>
  <div class="form-group">
    <%= f.input :public_status, as: :boolean, boolean_style: :inline %>
  </div>
  <%= f.button :submit, "Create card", class: 'btn btn-default' %>
<% end%>

app/views/cards/show.html.erb
<h1 class="title">
  <%= @card.title %>
</h1>

<p class="date">
  Submitted <%= time_ago_in_words(@card.created_at) %> Ago
  | <%= link_to 'Edit', edit_card_path(@card) %>
  | <%= link_to 'Delete', card_path(@card), method: :delete, data: {confirm: "Are you sure?"} %>
</p>

<p class="body">
  <%= markdown(@card.body) %>
</p>